global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

rule_files:
  - /etc/prometheus/alerts.yml
